meta_title: "Wakatapee - Keep your project on track 🚀"
meta_description: "Stay focus on what's really matters: deliverables"
meta_image: "meta.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@maxime_lemaitre" # indispensable pour les Twitter Cards
